// tokens:build — transform tokens/tokens.json (DTCG) into src/styles/tokens.css as a Tailwind v4
// @theme block, via Style Dictionary v5 + a custom format. GENERATED — never hand-edit tokens.css.
//
// Path D (2026-07-25): drive @theme for colours + breakpoints + spacing + radius + shadow.
// Typography is intentionally NOT emitted (line-heights/weights diverge from the shipped ramp and
// the Figma ramp is incomplete — see docs/frontend-audit.md "Typography token gap"). Its values
// still live in tokens.json (source of truth) and are guarded by the em-assertion below.
import StyleDictionary from 'style-dictionary'
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const tokens = JSON.parse(readFileSync(resolve(ROOT, 'tokens/tokens.json'), 'utf8'))

// ── em-assertion (Path D guard): tracking_px / size_px must equal the intended em per ramp step.
// Catches someone changing a size without updating tracking. Wired into CI via tokens:build.
const INTENDED_EM = { display: -0.02, h1: -0.02, h2: -0.01, h3: -0.01, 'body-lg': 0, body: 0, 'body-sm': 0, caption: 0, overline: 0.04 }
function assertTrackingEm(t) {
  const size = t.typography?.size || {}, tracking = t.typography?.tracking || {}
  const fails = []
  for (const step of Object.keys(INTENDED_EM)) {
    const sz = parseFloat(size[step]?.$value)
    const tr = Number(tracking[step]?.$value)
    if (!Number.isFinite(sz) || !Number.isFinite(tr)) { fails.push(`${step}: missing size/tracking`); continue }
    const em = Math.round((tr / sz) * 1000) / 1000
    if (Math.abs(em - INTENDED_EM[step]) > 1e-6) fails.push(`${step}: tracking ${tr}px / size ${sz}px = ${em}em, expected ${INTENDED_EM[step]}em`)
  }
  if (fails.length) { console.error('tokens:build FAILED — tracking em-assertion:\n  ' + fails.join('\n  ')); process.exit(1) }
  console.log(`em-assertion OK (${Object.keys(INTENDED_EM).length} ramp steps)`)
}
assertTrackingEm(tokens)

// ── custom @theme format ──────────────────────────────────────────────────────────
const v = (t) => (t.original && t.original.$value != null ? t.original.$value : t.value)
function themeFormat({ dictionary }) {
  const byCat = {}
  for (const t of dictionary.allTokens) (byCat[t.path[0]] = byCat[t.path[0]] || []).push(t)
  const colour = byCat.color || []
  const name = (t) => t.path.slice(1).join('-') // ["color","brand-blue-600"] -> "brand-blue-600"
  const L = []
  L.push('/* ============================================================================')
  L.push('   GENERATED by `npm run tokens:build` from tokens/tokens.json (Figma = source of truth).')
  L.push('   Do NOT edit by hand. Colours/breakpoints/spacing/radius/shadow only (Path D).')
  L.push('   Typography is a documented gap — see docs/frontend-audit.md.')
  L.push('   ============================================================================ */')
  // Two-layer: :root primitives (raw hex) so the app's semantic layer (var(--brand-blue-950)…) resolves.
  L.push(':root {')
  for (const t of colour) L.push(`  --${name(t)}: ${v(t)};`)
  L.push('}')
  // @theme inline: colours reference the primitive; scalar families carry the value directly.
  L.push('')
  L.push('@theme inline {')
  L.push('  /* Colours (Brand · Neutral · Semantic). --color-* -> bg-/text-/border- utilities. */')
  for (const t of colour) L.push(`  --color-${name(t)}: var(--${name(t)});`)
  const scalar = (cat, prefix, label) => {
    const list = byCat[cat] || []
    if (!list.length) return
    L.push(`  /* ${label} */`)
    for (const t of list) L.push(`  --${prefix}-${t.path[1]}: ${v(t)};`)
  }
  L.push('')
  scalar('breakpoint', 'breakpoint', 'Breakpoints (= Tailwind defaults)')
  scalar('spacing', 'spacing', 'Spacing (8pt grid; = Tailwind scale)')
  scalar('radius', 'radius', 'Radius — Figma-canonical (md/lg deliberately differ from Tailwind defaults)')
  scalar('shadow', 'shadow', 'Shadow — Figma-canonical (deliberately differ from Tailwind defaults)')
  L.push('}')
  return L.join('\n') + '\n'
}

const sd = new StyleDictionary({
  tokens,
  usesDtcg: true,
  platforms: {
    css: {
      transforms: ['name/kebab'],
      buildPath: 'src/styles/',
      files: [{ destination: 'tokens.css', format: 'css/servyou-theme' }],
    },
  },
  hooks: { formats: { 'css/servyou-theme': themeFormat } },
  log: { verbosity: 'silent' },
})
await sd.buildAllPlatforms()
console.log('tokens.css written -> src/styles/tokens.css')
